# Binary Iris Classification with a Neural Network

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Dataset

In [3]:
path = ""
dataSet = pd.read_csv(path+'iris.csv')
dataSet = dataSet[:100] # Keep the Iris-setosa and Iris-versicolor classes
# Shuffle the DataFrame
data = dataSet.sample(frac=1).reset_index(drop=True)

data[20:40]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
20,11,5.4,3.7,1.5,0.2,Iris-setosa
21,49,5.3,3.7,1.5,0.2,Iris-setosa
22,68,5.8,2.7,4.1,1.0,Iris-versicolor
23,85,5.4,3.0,4.5,1.5,Iris-versicolor
24,6,5.4,3.9,1.7,0.4,Iris-setosa
25,18,5.1,3.5,1.4,0.3,Iris-setosa
26,89,5.6,3.0,4.1,1.3,Iris-versicolor
27,71,5.9,3.2,4.8,1.8,Iris-versicolor
28,20,5.1,3.8,1.5,0.3,Iris-setosa
29,69,6.2,2.2,4.5,1.5,Iris-versicolor
30,39,4.4,3.0,1.3,0.2,Iris-setosa
31,75,6.4,2.9,4.3,1.3,Iris-versicolor
32,62,5.9,3.0,4.2,1.5,Iris-versicolor
33,17,5.4,3.9,1.3,0.4,Iris-setosa
34,77,6.8,2.8,4.8,1.4,Iris-versicolor
35,32,5.4,3.4,1.5,0.4,Iris-setosa
36,58,4.9,2.4,3.3,1.0,Iris-versicolor
37,21,5.4,3.4,1.7,0.2,Iris-setosa
38,87,6.7,3.1,4.7,1.5,Iris-versicolor
39,84,6.0,2.7,5.1,1.6,Iris-versicolor

In [4]:
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-setosa", "0"))
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-versicolor", "1"))
data = data.astype(float)
data[:20]

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   34.0            5.5           4.2            1.4           0.2      0.0
1   37.0            5.5           3.5            1.3           0.2      0.0
2    8.0            5.0           3.4            1.5           0.2      0.0
3    3.0            4.7           3.2            1.3           0.2      0.0
4   59.0            6.6           2.9            4.6           1.3      1.0
5   54.0            5.5           2.3            4.0           1.3      1.0
6   43.0            4.4           3.2            1.3           0.2      0.0
7    7.0            4.6           3.4            1.4           0.3      0.0
8   26.0            5.0           3.0            1.6           0.2      0.0
9   10.0            4.9           3.1            1.5           0.1      0.0
10  95.0            5.6           2.7            4.2           1.3      1.0
11  41.0            5.0           3.5            1.3           0.3      0.0
12  65.0            5.6           2.9            3.6           1.3      1.0
13  29.0            5.2           3.4            1.4           0.2      0.0
14  25.0            4.8           3.4            1.9           0.2      0.0
15  23.0            4.6           3.6            1.0           0.2      0.0
16  16.0            5.7           4.4            1.5           0.4      0.0
17  94.0            5.0           2.3            3.3           1.0      1.0
18  98.0            6.2           2.9            4.3           1.3      1.0
19  31.0            4.8           3.1            1.6           0.2      0.0

In [5]:
X = data.iloc[:,1:5].values # Feature columns
y = data.iloc[:,5:6].values # Target column
y = y.astype(int)
print(X[:5])
print(y[:5])

print(np.shape(X))
print(np.shape(y))

[[5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.  3.4 1.5 0.2]
 [4.7 3.2 1.3 0.2]
 [6.6 2.9 4.6 1.3]]
[[0]
 [0]
 [0]
 [0]
 [1]]
(100, 4)
(100, 1)

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, 
    y,
    test_size = 0.2,
    random_state=10
)
print(len(data))
print(len(x_train))
print(len(x_test))

100
80
20

## TensorFlow model

### Architecture

In [7]:
model = Sequential(
    [ 
        Dense(4, activation = 'relu', name = 'layer1'),
        Dense(1, activation = 'sigmoid', name = 'layer2')    
    ]
)

In [8]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.01),
)

model.fit(
    x_train, y_train, 
    epochs=100
)

Epoch 1/100

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3.8054
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2332
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5454
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.9959
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6657
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0944
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8278
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5528
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4927
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4277
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4234
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4428
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4530
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4503
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4515
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4524
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4311
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4206
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4153
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4100
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3946
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4038
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3911
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3853
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3803
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3775
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3779
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3719
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3802
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3576
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3520
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3552
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3536
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3490
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3351
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3331
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3197
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3140
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3233
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3248
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3195
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3045
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2968
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3068
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3016
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2875
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2749
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2880
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2755
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2740
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2753
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2640
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2573
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2481
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2492
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2524
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2422
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2419
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2365
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2278
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2226
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2157
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2171
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2255
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2183
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2063
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2111
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2066
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2042
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2065
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1873
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2002
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1865
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1871
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1867
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1808
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1732
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1800
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1744
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1786
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1684
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1671
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.16334
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1619
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1544
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1598
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1573
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1508
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1515
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1511
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1394
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1463
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1462
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1380
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1417
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1404
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1368
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1267
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1292
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1299

The `model.summary()` provides a description of the network:

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 77 (312.00 B)

 Trainable params: 25 (100.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 52 (212.00 B)

In [10]:
loss = model.evaluate(x_test, y_test)
print(loss)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.1042
0.10415945202112198

The parameter counts shown in the summary correspond to the number of elements in the weight and bias arrays as shown below.

In [11]:
L1_num_params = 4 * 4 + 4   # W1 and b1 parameters
L2_num_params = 4 * 1 + 1   # W2 and b2 parameters
print("L1 params = ", L1_num_params, ", L2 params = ", L2_num_params  )

L1 params =  20 , L2 params =  5

### Performance Analysis

In [12]:
predictions = model.predict(x_test)
accuracy = tf.keras.metrics.CategoricalAccuracy()(y_test, predictions).numpy()
print(f'Accuracy: {accuracy * 100:.2f}%')

# Reference: https://www.tensorflow.org/api_docs/python/tf/keras/metrics/CategoricalAccuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Accuracy: 100.00%

In [13]:
binaryPred = (predictions>0.5).astype(int)

for i in range(len(y_test)):
    print("Actual: %d - Pred: %d"%(y_test[i], binaryPred[i]))

Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1
Actual: 0 - Pred: 0
Actual: 1 - Pred: 1

In [14]:
print("Generate a prediction for a single sample")
sample1 = np.array([5.1, 2.5, 3.0, 1.1]) # Class 1: Iris-versicolor
sample2 = np.array([4.4, 3.0, 1.3, 0.2]) # Class 0: Iris-setosa

sample = sample2.reshape((1,len(sample1)))
predSample = model.predict(sample)

print(f"Prediction: {predSample}")
print(f"Prediction: {(predSample>0.5).astype(int)}")

Generate a prediction for a single sample
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Prediction: [[0.07053322]]
Prediction: [[0]]

In [15]:
print("Generate predictions")
predSamples = model.predict_step(x_test[:5])
predSamples = (predSamples>0.5)
print(f"\nPrediction:\n {predSamples}")

Generate predictions

Prediction:
 [[False]
 [False]
 [False]
 [False]
 [ True]]